module.exports = {
  // activeIngredientsTable: require('./product/get.activeIngredients.table.json'),
  // productsTable: require('./product/get.products.table.json'),
  // categoriesTable: require('./product/get.categories.table.json'),
  // therapiesTable: require('./product/get.therapies.table.json'),
  // routesTable: require('./product/get.routes.table.json'),
  // categoryTradesTable: require('./product/get.categoryTrades.table.json'),
  // colorsTable: require('./product/get.colors.table.json'),
  // characteristicsTable: require('./product/get.characteristics.table.json'),
  // packagesTable: require('./product/get.packages.table.json'),
  // countriesTable: require('./product/get.countries.table.json'),
  // pharmacologicalMechanismsTable: require('./product/get.pharmacologicalMechanisms.table.json'),
  // pharmacologicalImpactsTable: require('./product/get.pharmacologicalImpacts.table.json'),
  // unitsTable: require('./product/get.units.table.json'),
  // toxicitiesTable: require('./product/get.toxicities.table.json'),
  // productGroupsTable: require('./product/get.productGroups.table.json'),
  // odorsTable: require('./product/get.odors.table.json'),
  // otherCharacteristicsTable: require('./product/get.otherCharacteristics.table.json'),
  // enterprisesTable: require('./product/get.enterprises.table.json'),
  // categoryLabelsTable: require('./product/get.categoryLabels.table.json'),
  // usesTable: require('./product/get.uses.table.json'),
  // chemicalStructuresTable: require('./product/get.chemicalStructures.table.json'),
  // fdaPharmacologicalGroupsTable: require('./product/get.fdaPharmacologicalGroups.table.json'),
  // snomedCategoriesTable: require('./product/get.snomedCategories.table.json'),
  // shapesTable: require('./product/get.shapes.table.json'),

  // store
  store: require('./store/list.store.json'),
  inventory: require('./store/list.inventory.json')
}